# Generated by Django 4.0.3 on 2022-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.TextField()),
                ('people', models.CharField(max_length=30)),
                ('phone', models.TextField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.RenameField(
            model_name='appetizeritems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='baoitems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dessertitems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dimsumitems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='drinkitems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='noodlesoupitems',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sushiitems',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='sushiitems',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
