# Generated by Django 4.0.3 on 2022-03-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='notification',
        ),
    ]
